from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class LLMOutputSanitizerInput(BaseModel):
    raw_output: str = Field(..., description="Raw text output generated by the LLM")
    system_prompt_reference: str = Field(default="", description="Reference to original system prompt guidelines")


class LLMOutputSanitizerOutput(BaseModel):
    is_secure: bool = Field(..., description="True if no prompt injection/override vectors are detected")
    sanitized_output: str = Field(..., description="Processed, safe, and scrubbed output string")
    risk_score: float = Field(..., description="Calculated security risk score from 0.0 to 100.0")
    detected_leaks: List[str] = Field(default_factory=list, description="List of identified instruction leak types")
    status: str = Field(..., description="Operational compliance status")


class PiLLMOutputSanitizer:
    """Specialized LLM Response Sanitizer enforcing instruction safety boundaries and leak mitigation."""

    def __init__(self) -> None:
        self.agent_name = "PiLLMOutputSanitizer"

    def sanitize_llm_output(self, input_envelope: LLMOutputSanitizerInput) -> LLMOutputSanitizerOutput:
        raw = input_envelope.raw_output
        leaks = []
        risk_score = 0.0
        sanitized = raw

        # Check for system instruction leaks
        system_triggers = [
            "you are a helpful assistant",
            "system prompt",
            "internal guidelines",
            "ignore previous instructions",
        ]
        for trigger in system_triggers:
            if trigger in raw.lower():
                leaks.append(f"Detected potential system prompt exposure trigger: '{trigger}'")
                risk_score += 35.0

        # Check for standard credential leaks
        if any(tok in raw.lower() for tok in ["api_key", "bearer ", "aws_access"]):
            leaks.append("Detected leaked authorization token in output.")
            risk_score += 45.0
            # Simple scrub
            sanitized = sanitized.replace("api_key", "[REDACTED_API_KEY]")

        risk_score = min(risk_score, 100.0)
        is_secure = risk_score < 40.0
        status = "CLEAN" if is_secure else "COMPROMISED"

        return LLMOutputSanitizerOutput(
            is_secure=is_secure, sanitized_output=sanitized, risk_score=risk_score, detected_leaks=leaks, status=status
        )
