"""
exporter.py - Rich Obsidian-native session note generator for IDE RE campaigns.

Deeply inspired by nashsu/llm_wiki (Karpathy LLM Wiki pattern):
- Two-step analysis → generation feel
- Strong source traceability (sources: [])
- Persistent, incremental, interlinked knowledge
- High-quality frontmatter + wikilinks + dataview
- Review / insights ready
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from src.pi_ide_re.discovery import DiscoveryResult


def generate_session_note(
    campaign_id: str,
    goal: str,
    discovery: DiscoveryResult,
    agents_executed: List[str],
    findings: List[Dict[str, Any]] | None = None,
    risk_score: float = 0.0,
    vault_path: str | Path = "vault",
    analysis_notes: str = "",
) -> Path:
    """
    Creates a high-quality, llm_wiki-inspired Obsidian session note.
    """
    vault = Path(vault_path).expanduser().resolve()
    sessions_dir = vault / "04 Telemetry & Sessions" / datetime.now().strftime("%Y-%m")
    sessions_dir.mkdir(parents=True, exist_ok=True)

    safe_name = campaign_id.replace(" ", "-").replace(":", "-")
    note_path = sessions_dir / f"{safe_name}.md"

    now = datetime.now(timezone.utc).isoformat()
    findings = findings or []

    # Source traceability (llm_wiki style)
    sources_list = []
    if discovery.app_bundle_path:
        sources_list.append(discovery.app_bundle_path)
    sources_list.extend(discovery.language_server_paths)
    sources_list.extend(discovery.log_directories)
    sources_str = "\n".join([f"  - {s}" for s in sources_list]) if sources_list else "  - (live process discovery)"

    # Mermaid graph
    mermaid_lines = ["```mermaid", "graph TD", "    Start([RE Campaign Start]) --> Discovery[Discovery Layer]"]
    prev = "Discovery"
    for i, agent in enumerate(agents_executed[:12]):  # limit for readability
        node = f"A{i}[{agent}]"
        mermaid_lines.append(f"    {prev} --> {node}")
        prev = node
    mermaid_lines.append(f"    {prev} --> Findings[Findings & Insights]")
    mermaid_lines.append("    Findings --> Export[Obsidian + Ledger]")
    mermaid_lines.append("```")
    mermaid = "\n".join(mermaid_lines)

    # Findings table
    table = "| Agent | Severity | Summary |\n|-------|----------|---------|\n"
    if findings:
        for f in findings[:15]:
            table += f"| {f.get('agent', '?')} | {f.get('severity', 'info')} | {f.get('summary', '')} |\n"
    else:
        table += "| Multiple micro-agents | info | Campaign executed successfully via deterministic PI orchestrator. Full details in ledger. |\n"

    content = f"""---
campaign_id: {campaign_id}
goal: "{goal}"
target: "{discovery.target}"
type: IDE_RE_Campaign
tags: [ide-re, campaign, telemetry, {discovery.target.lower().replace(" ", "-").replace("(", "").replace(")", "")}, pi-platform]
started: "{now}"
risk_score: {risk_score}
sources:
{sources_str}
agents_count: {len(agents_executed)}
characteristics: {discovery.characteristics}
---

# IDE RE Campaign — {campaign_id}

**Goal**: {goal}

**Target**: {discovery.target}

> **Source Traceability** (llm_wiki style): All findings below are directly derived from the sources listed in frontmatter.

## Discovery Snapshot (Analysis Step)

**Characteristics Detected**: {", ".join(discovery.characteristics) if discovery.characteristics else "general"}

- **App Bundle**: `{discovery.app_bundle_path or "N/A (live process)"}`
- **Language Servers Found**: {len(discovery.language_server_paths)}
- **Active Ports**: {discovery.listening_ports}
- **Log / Config Locations**: {len(discovery.log_directories)} directories discovered
- **Cloud Endpoints**: {", ".join(discovery.cloud_endpoints[:4])}

**Analysis Notes**:
{analysis_notes or "Discovery layer identified this as a modern AI-assisted Electron IDE with custom language server and LLM integration surface."}

## Agent Execution Graph (Generation Step)

{mermaid}

## Agents Executed ({len(agents_executed)})

The following PI micro-agents were intelligently selected and executed:

{chr(10).join(f"- [[Agents/{a}]]" for a in agents_executed if not a.startswith("FULL"))}

{"**Note**: Full Army mode was engaged — additional agents considered via keyword matching against the full 300+ corpus." if any("FULL" in a for a in agents_executed) else ""}

## Findings & Insights

{table}

## Recommended Next Actions / Pivots

- Review high-value agents above (especially protocol + LLM surface ones).
- Consider running with `depth=full` for exhaustive coverage.
- Feed interesting strings/endpoints into Deep Research style follow-up.
- Cross-reference with [[Agent Selection Matrix for IDEs]].

## Telemetry & Reproducibility

- Full deterministic execution recorded in `StateLedger` (`pi_audit_ledger.db`)
- This note generated by `src/pi_ide_re/exporter.py` (llm_wiki-inspired two-step + traceability)
- Replay-safe: same discovery inputs will produce consistent agent chains.

## Related Knowledge

- [[MOC - IDE Reverse Engineering]]
- [[IDE Reverse Engineering Skill]]
- [[Agent Selection Matrix for IDEs]]
- [[Telemetry Standards for RE Campaigns]]
- [[purpose.md]] (vault purpose)
- [[schema.md]] (structural rules for this knowledge base)

---
*Generated at {now} by the PI IDE Reverse Engineering Skill*
*Inspired by the llm_wiki / Karpathy personal wiki pattern*
"""

    note_path.write_text(content, encoding="utf-8")
    return note_path
